name: Generate README.md

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP & Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'

    - name: Install Dependencies for Production
      run: composer install --no-dev --optimize-autoloader

    - name: Easy Coding Standard
      run: php vendor/bin/ecs

    - name: Generate README.md
      run: php bin/readme

    - name: Configure Git
      run: |
        git config --global user.name "Pierre Arnissolle"
        git config --global user.email "pierre@arnissolle.com"

    - name: Check for changes and commit
      run: |
        git diff --exit-code || (git commit -am "Update README.md from GitHub Actions" && git push)
